apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: eva

spec:
  generators:
    - list:
        elements:
          - url: https://kubernetes.default.svc
            short: dev
  template:
    metadata:
      name: 'eva-{{short}}'
      annotations:
        notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: eva
        argocd.argoproj.io/manifest-generate-paths: '/manifests/eva'
        codefresh.io/product: example-voting-app
        codefresh.io/app-group: eva
    spec:
      project: default
      source:
        repoURL: https://github.com/briggs-octo/DevOps.git
        targetRevision: main
        path: manifests/eva
        helm:
          valueFiles:
            - "{{short}}/values.yaml"
      destination:
        namespace: '{{short}}'
        server: '{{url}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=false
          - CreateNamespace=true
