loans:
  image:
    repository: docker.io/aperturesci/orders
    tag: main-2a489a5
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi
